@echo off
REM =============================================================================
REM Activate Fabric CICD Environment - fabric-cicd
REM =============================================================================
REM This file is auto-generated by setup_fabric_cicd.bat
REM To regenerate: run setup_fabric_cicd.bat

echo 🚀 Activating Fabric CICD environment: fabric-cicd...
call conda activate fabric-cicd
if errorlevel 1 (
    echo ❌ Failed to activate environment
    echo 💡 Run setup_fabric_cicd.bat to create the environment
    pause
    exit /b 1
)

echo ✅ Environment activated successfully!
echo 💡 You can now run Fabric CICD commands
echo.
if exist "%USERPROFILE%\Miniconda3\Scripts\activate.bat" (
    call "%USERPROFILE%\Miniconda3\Scripts\activate.bat" fabric-cicd
    if %errorlevel%==0 (
        echo ✅ Successfully activated using user profile Miniconda3
        goto :success
    )
)

REM If all attempts fail
echo ❌ Could not activate fabric-cicd environment
echo.
echo 💡 Please try one of these solutions:
echo    1. Make sure conda is added to your PATH
echo    2. Create the environment manually: conda create -n fabric-cicd python=3.12.11
echo    3. Run this from an Anaconda Prompt instead
echo.
pause
exit /b 1

:success

REM Show environment info
echo ✅ Environment activated!
echo 📋 Environment: fabric-cicd
echo 🐍 Python version:
python --version
echo.

REM Test fabric-cicd availability
echo 🧪 Testing fabric-cicd installation...
python test_environment.py

echo.
echo 🎯 You're now ready to use Fabric CICD!
echo.
echo 📚 Available scripts:
echo    python fabric_deploy_local.py --help    # Deploy from local repository
echo    python fabric_deploy_devops.py --help   # Deploy from Azure DevOps
echo    deploy_from_devops.bat                   # Interactive DevOps deployment
echo.
echo 💡 To deactivate: conda deactivate
echo.

REM Keep the command prompt open in the activated environment
cmd /k
