name: fabric-cicd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - git
  - pip:
      - fabric-cicd>=0.1.23
      - azure-identity>=1.15.0
      - PyYAML>=6.0
      - click>=8.0.0
      - python-dotenv>=1.0.0
      - colorlog>=6.0.0
